[package]
name = "mythmallow-enemies-sweet"
version = "0.0.0"
edition = "2021"

[dependencies]
mythmallow = { path = "../../game", package = "mythmallow-game" }
survival-mode = { path = "../../modes/survival", package = "mythmallow-mode-survival" }

[lints]
workspace = true
