[package]
name = "mythmallow-players-greek"
version = "0.0.0"
edition = "2021"

[dependencies]
mythmallow = { path = "../../game", package = "mythmallow-game" }
greek-items = { path = "../../items/greek", package = "mythmallow-items-greek" }
